### ISSUE TITLE
Session stuff.

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#19]
1.) Login redirects do not actually redirect to the location set in the URL. The user is just redirected to /
2.) Users are logged in for 15-30mins before being logged out. Need to set that longer.

**Comment by ericadeefox** [comment]
Whoops you were totally right. Better get my cookies together.

**Comment by ericadeefox** [comment]
Gonna leave this guy up for the night, and make sure that the new cookie middleware actually works.

**Comment by PhantomWatson** [comment]
Closing; assumed to have been fixed
