### ISSUE TITLE
WCAG adherence

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#41]
This issue is for documenting the ways that our web infrastructure [needs updated for accessibility compliance](https://www.employerlawreport.com/2015/12/articles/eeo/website-accessibility-regulations-delayed-until-2018-but-businesses-should-not-table-the-issue-until-then/).

Here are some resources:
[http://ffoodd.github.io/a11y.css/](http://ffoodd.github.io/a11y.css/)
[https://webaim.org/resources/contrastchecker/](https://webaim.org/resources/contrastchecker/)
[http://wave.webaim.org/report#/https://muncieevents.com](http://wave.webaim.org/report#/https://muncieevents.com)

**Comment by PhantomWatson** [comment]
Closing; issue not necessary for saving links for reference
