### ISSUE TITLE
"#" selector for alphabetized tags & locations lists not working.

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#49]
**Note: it's like this in the 2.x version as well.**

If you click the "#" selector in the tags breakdown by letter, or the new locations breakdown by letter, you won't get any of the tags or locations that start with numbers. I think with how it's written, it's looking for tags & locations that literally start with the hash symbol.

**Comment by PhantomWatson** [comment]
Yeah, [the HTML specs say](https://stackoverflow.com/a/79022/52530) that element IDs can't start with numbers. :(

**Comment by ericadeefox** [comment]
Hmmn. I wonder if there's some voodoo I could whip up that categorizes numerical tags & locations by the letter that those numbers start with! e.g. 2 Johnny's gets put into T, 111 gets put into O, etc.

**Comment by ericadeefox** [comment]
Production site: `/tags/past` no longer works........ It works locally on my workstation, but not on the production site.

**Comment by ericadeefox** [comment]
`2018-01-18 16:07:18 Error: Fatal Error (1): Allowed memory size of 33554432 bytes exhausted (tried to allocate 20480 bytes)` yikes.
