### ISSUE TITLE
1.1 second long server response time

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#53]
Oh boy do we need to optimize this site:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmuncieevents.com%2F

**Comment by ericadeefox** [comment]
![image](https://user-images.githubusercontent.com/12422542/35166818-245e3ed2-fd21-11e7-94ff-51e65ad0e5b9.png)

advice from Jose.

**Comment by PhantomWatson** [comment]
Closing; speed optimization will be ongoing and will need to be reevaluated after CakePHP 3 overhaul is complete
