### ISSUE TITLE
Unapproved events not showing up in moderation: the saga

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#56]
So, at  23:27 on Saturday, Graham DM-ed me this screenshot...

![image](https://user-images.githubusercontent.com/12422542/35225518-9cf09a02-ff56-11e7-802b-47b114ef622c.png)

... and told me to check into it on Monday. So, here's Monday, and I'm checking into it. I see now that we have four unapproved events...

![image](https://user-images.githubusercontent.com/12422542/35225583-c54e4922-ff56-11e7-846f-df5cfd73d119.png)

... and I'm starting to get a little bit suspicious. Does... anyone at 111 care about the Pats? Anyone in Muncie? No? Well, then that's suspicious! Even more suspicious: I look at phpMyAdmin and discover that the three events that needed moderation, are blank:

![image](https://user-images.githubusercontent.com/12422542/35225977-d6c71c64-ff57-11e7-9312-6200f05f2e11.png)

So I'm thinking this is not an issue of code, of whether or not `Events.moderate()` is actually querying for the right events to moderate, but of security... I will look into this further.

**Comment by ericadeefox** [comment]
A quick jaunt through the `users` table reveals many weird-TLD emails, some very spam-my rows. Not very encouraging. The thing of it is: the _existence_ of spam users dates back years, but the creation of spam accounts has ramped up significantly since the 3.x switch. Of the eight accounts that have been made since the switch, a full half of them are spam accounts.

Front-end validation and front-end spam control are working.

**Comment by ericadeefox** [comment]
So, that's obvious. To prevent spam on the user side of things, I'll do these things today:

- [ ] Fix Recaptcha. Obvi. There's a new 3.x cake-recaptcha plugin I'm gonna try out.
- [ ] Go through and disable all the existing spam accounts (most of them will not be logged into after creation, as their data suggests...)
- [ ] Perhaps we ought to begin moderating users just as we moderate events?

As far as those three blank events, I have less experience/familiarity with what could be behind that, and would need to think about it more deeply.

**Comment by ericadeefox** [comment]
Hm....... even after the plugin switch, Recaptcha still does not appear to be working.

**Comment by ericadeefox** [comment]
Weird sad update: Recaptcha works on my workstation locally but not on production.

**Comment by ericadeefox** [comment]
Even after updating the site & secret keys, Recaptcha does not do its job at all...

**Comment by ericadeefox** [comment]
The last 4 commits should reference issue #58.

**Comment by ericadeefox** [comment]
Commit 21f63c4 is meant for issue #59. Wow, I swear...

**Comment by ericadeefox** [comment]
Added the ongoing label as we monitor the situation.

**Comment by PhantomWatson** [comment]
This appears to be fixed.

**Comment by PhantomWatson** [comment]
This does not appear to be fixed.
![image](https://user-images.githubusercontent.com/1965565/50652922-f7783d80-0f55-11e9-9173-cb0776ed432c.png)
