### ISSUE TITLE
Allow cron job to send mailing list emails

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie-events3#64]
Currently, `MailingListController` requires users to log in to access `/mailing-list/send-daily`, resulting in the cron job request being redirected to `/login?redirect=%2Fmailing-list%2Fsend-daily` and not sending daily or weekly emails.

**Comment by ericadeefox** [comment]
I'm not sure how to test this but I think I got it.

**Comment by PhantomWatson** [comment]
When I need to quickly test an anonymous user being able to access a page, I just open up a private/incognito browser window and paste the URL into it. It saves some steps versus logging out, accessing the URL, finishing testing, and logging back in.

**Comment by ericadeefox** [comment]
Oh, anonymous users are totally able to access the page now.

**Comment by ericadeefox** [comment]
```
2018-01-25 03:07:04 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at /home/okbvtfr/public_html/muncie_events_cakephp3/src/Model/Table/MailingListTable.php:683) in [/home/okbvtfr/public_html/muncie_events_cakephp3/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 181]
Request URL: /mailing-list/send-weekly
```

Most recent mailing-list related error message.......

**Comment by ericadeefox** [comment]
Actually physically going to these URLs triggers nothing.

**Comment by PhantomWatson** [comment]
Closing; this appears to be fixed, and the sending of emails should be moved from a controller action to a command-line script anyway.
