### ISSUE TITLE
New features for user images

### ISSUE THREAD

**Issue by ericadeefox** [BallStateCBER/muncie-events3#7]
In the Cake3 version of Muncie Events, users will be able to upload images for their profiles, awesome! Here are some new features to be added:

- [ ] Expand the user images when you click on them, just like how you can do that on the events images.
- [ ] Show thumbnails of users' previously uploaded images.
- [ ] Allow the user to select from their previously uploaded images which one they'll feature on their profile.

**Comment by PhantomWatson** [comment]
Closing; not currently on the planned feature list
